version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobtracker_user
      POSTGRES_PASSWORD: jobtracker_password
      POSTGRES_DB: jobtracker
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
